### PR TITLE
docs: add guide for setting up testing environment in Telegram

### LINKED ISSUE #2: Setup testing environment for the mini-app in Telegram
Figure out how testing environment in TG work, and write a detailed guide for future contributors on how to configure it.

Requirements:
- the guide, should be clear and complete
- an example on how you configured it for yourself

### PR DESCRIPTION
**Pull request by josephchimebuka**
Closes #2 

## Summary by CodeRabbit

- **New Features**
	- Added a "Setting Up the Build Environment" section in the README for configuring the development environment.
	- Introduced a "Setting up Testing Environment for Telegram Bots" section in SETUP.md to guide users on testing Telegram bots.
	- Created a new comprehensive guide in docs/telegram-setup.md for setting up a testing environment for Telegram bots.

- **Documentation**
	- Enhanced documentation structure and content for better user guidance, including detailed instructions on environment variables.

### CODE REVIEW

**Comment by kfastov** [comment]
@josephchimebuka 
Good job! Can you please add a paragraph about env variables configuration, like BOT_TOKEN and WEBAPP_URL?
It would be super duper cool if you also modify the existing docs like README or SETUP to reference this new doc.

**Comment by josephchimebuka** [comment]
Thank you @kfastov I'll get on it in the evening currently on transit

**Comment by kfastov** [comment]
@josephchimebuka please resolve merge conflicts, I'll merge it as is

**Comment by kfastov** [comment]
Good, thank you @josephchimebuka

**Pull request merged**
