### PR TITLE
Implement improved signature verification and error handling for acco…

### PR DESCRIPTION
**Pull request by ShantelPeters**
…unt and factory contracts

## Release Notes

- **New Features**
	- Introduced Telegram authentication module with user data handling.
	- Added biometric authentication component for enhanced security.
	- Implemented a method for verifying Telegram signatures and executing transfers.

- **Bug Fixes**
	- Improved error handling for authentication processes and signature validation.

- **Documentation**
	- Added a new configuration file for web application components.

- **Chores**
	- Updated dependencies in the project to enhance functionality and performance.
	- Refactored CSS for better maintainability and dark mode support.

- **Style**
	- Enhanced global styles with comprehensive CSS variables for light and dark themes.

### CODE REVIEW

**Comment by kfastov** [comment]
Hi! Do you know you didn't have to implement contracts? The goal of the issue was to create signatures (or other type of proofs) inside mini-app that can prove account ownership. There are other issues for contracts. Don't delete it btw, maybe the code will be usable for ppl doing those contracts

**Comment by kfastov** [comment]
Sorry, it doesn't seem relevant to #6 and we don't have time for improvements cause it's a blocker issue, so I am taking over the issue, and will consider this PR as a dummy implementation of contracts (to be replaced by real implementations from #3 and #8 )

**Comment by ShantelPeters** [comment]
> @ShantelPeters Is it ready for review? Do you plan adding real signature logic to the mini-app?

No sir it’s not ready for review still working on it @kfastov

**Review by kfastov — CHANGES_REQUESTED** [review]
Good job. Validation route will be useful as a basis for telegram user verification.
Please remove commented out code if it isn't used, or uncomment otherwise

**Pull request merged**
